### ISSUE TITLE
Doesn't work with ajax or remote links

### ISSUE THREAD

**Issue by octavpo** [jarthod/render-later#3]
It seems for ajax or remote links I do get the response displayed correctly if I'm careful to have a = render_now in the result template, but it will wait until the whole result is received before displaying any part of it. Is there a way to make it show the result streamed? Thanks.

**Comment by jarthod** [comment]
Yes, because your ajax call don't stream the response. it waits for the full response and inserts it all at once into the DOM. It's possible but tricky to do streaming in AJAX: https://stackoverflow.com/questions/7740646/jquery-ajax-read-the-stream-incrementally, all standard ajax functions (`jQuery` or `rails-ujs` for example) won't support streaming.

I never tried it but I think if you use one of these streaming examples and append whatever you received as soon as possible in the DOM it should have the expected streaming effect. But I'm not sure if it's worth the trouble for you :)

If you have a page with slow sections which takes great advantage of `render-later`, it may be simpler to just drop the AJAX here and benefit from the simple native html streaming instead.

**Comment by octavpo** [comment]
Yes I tried this recently with using just 'stream: true' on the server side, and I couldn't make it work, maybe for the same reason the regular streaming doesn't work (which I still haven't identified). Or maybe it needs more work on the server side, like using a live connection, and then it's really not worth it, I'd have to do it in about 20-30 different places.

What I was wondering is if your utility could provide some js function that I could call in the 'onprogress' event that would make it work for ajax calls. Btw can you give me more details about how your utility works? Maybe that would help me understand why yours work while the regular streaming doesn't for html requests. Thanks.

**Comment by jarthod** [comment]
I just noticed I haven't replied to this last comment ^^ You may not be interested now but I'm gonna answer in case it can help somebody.

You should check the readme of the project (https://github.com/jarthod/render-later) and especially the "Gotcha" sections for various pointers about what may be breaking HTTP streaming in Rails and how to workaround it. It's not easy unfortunately as the Rails maintainers are not very interested in steaming for the moment apparently.

This library does not provide any help to make streaming Ajax calls as it's purpose is to avoid Ajax calls entirely and make things much faster by using streaming instead. So sorry but if that's what you're looking for it's not there ;)
